name: Deploy

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
        with: 
          persist-credentials: false
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install
      - name: Build prod
        run: npm run build
      - name: Deploy to server
        uses: up9cloud/action-rsync@master
        env:
          TARGET: ${{ secrets.PATH }}
          SOURCE: /home/runner/work/app-pos-counter/app-pos-counter/workspace/build
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          ARGS: -avzrut --delete --exclude=/.git/ --exclude='.env' --exclude=/.github/
          POST_SCRIPT: |
            pm2 restart counterpos
          # POST_SCRIPT: |
          #   cd ${{ secrets.PATH }} && cd ../scripts && sh deploy.sh
